<!-- saved from url=(0022)http://internet.e-mail -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>

	<head>
		<title>Politicas de Privacidad</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link rel="stylesheet" type="text/css" href="resources/css/politicas.css">
	</head>	
	<body>
		<div class="headerPoliticas">
			<h1 class="tittle2-text">PORTAL DISTRIBUIDORES TELCEL</h1>
			<h2>POL&Iacute;TICAS DE PRIVACIDAD</h2>
		</div>
		<div class="contenidoPoliticas">
			<h3>POL&Iacute;TICAS DE PRIVACIDAD</h3>
			<p>
				TELCEL SE COMPROMETE A PROTEGER LA PRIVACIDAD DEL DISTRIBUIDOR EN LA 
          		P&Aacute;GINA DE TELCEL Y A FACILITAR LA TECNOLOG&Iacute;A DE DESARROLLO 
          		NECESARIA PARA QUE PUEDA DISFRUTAR DE UNA CONEXI&Oacute;N SEGURA Y EFICAZ. 
          		LA PRESENTE DECLARACI&Oacute;N DE PRIVACIDAD ES APLICABLE A ESTE PORTAL 
          		Y CONTEMPLA LA RECOPILACI&Oacute;N Y EL USO DE DATOS EN EL MISMO. AL 
          		OBTENER ACCESO AL PORTAL DE DISTRIBUIDORES DE TELCEL, EL DISTRIBUIDOR 
          		MANIFIESTA SU CONSENTIMIENTO CON EL TRATAMIENTO DE LOS DATOS A QUE SE 
          		REFIERE ESTA DECLARACI&Oacute;N.
			</p>
			<p>
				LEA LA DECLARACI&Oacute;N DE PRIVACIDAD DE TELCEL EN SU TOTALIDAD, 
          		PUES MEDIANTE &Eacute;STA SE HACE CONSTAR QUE SU INFORMACI&Oacute;N 
          		PERSONAL SER&Aacute; MANTENIDA EN CONFIDENCIALIDAD Y QUE USTED EST&Aacute; 
          		DE ACUERDO CON EL MANEJO DE LA MISMA.
			</p>
			<h3>RECOPILACI&Oacute;N DE INFORMACI&Oacute;N PERSONAL</h3>
			<p>
				EN ESTE SITIO WEB DE TELCEL SE RECOPILA INFORMACI&Oacute;N PERSONAL 
          		QUE IDENTIFICA AL DISTRIBUIDOR QUE LA PROPORCIONA, TAL COMO DIRECCI&Oacute;N 
          		DE CORREO ELECTR&Oacute;NICO, NOMBRE DEL DISTRIBUIDOR, N&Uacute;MERO 
          		CELULAR, N&Uacute;MERO DE CUENTA DE CONTRATO, DOMICILIO PARTICULAR O 
         		DE TRABAJO, CLAVE DEL REGISTRO FEDERAL DE CONTRIBUYENTES, EDAD, SEXO 
          		Y TODA AQUELLA INFORMACI&Oacute;N QUE TELCEL CONSIDERE NECESARIA PARA 
          		ESTAR EN POSIBILIDAD DE OFRECER UN MEJOR SERVICIO.
			</p>
			<p>
				TELCEL PUEDE RECOPILAR DE FORMA AUTOM&Aacute;TICA INFORMACI&Oacute;N 
          		SOBRE EL HARDWARE Y EL SOFTWARE DE SU EQUIPO. ENTRE LOS DIVERSOS DATOS 
          		QUE PUEDEN SER RECOPILADOS, SE ENCUENTRAN LA DIRECCI&Oacute;N IP, TIPO 
          		DE EXPLORADOR, NOMBRES DE DOMINIO, TIEMPO DE ACCESO, ETC&Eacute;TERA. 
          		TELCEL UTILIZAR&Aacute; DICHA INFORMACI&Oacute;N PARA ADMINISTRAR EL 
          		SERVICIO QUE PROPORCIONA A LOS DISTRIBUIDORES, PARA MANTENER LA CALIDAD 
          		DE DICHO SERVICIO Y PARA LA OBTENCI&Oacute;N DE ESTAD&Iacute;STICAS. 
          		RECUERDE QUE TODA INFORMACI&Oacute;N PERSONAL QUE IDENTIFICA AL DISTRIBUIDOR, 
          		REVELADA DE MANERA DIRECTA O POR CUALQUIER MEDIO DE CONTACTO O FORO 
          		P&Uacute;BLICO DE CONEXI&Oacute;N EN L&Iacute;NEA, PODR&Aacute; SER 
          		RECOPILADA Y UTILIZADA POR TELCEL.
			</p>
			<h3>USO DE INFORMACI&Oacute;N PERSONAL</h3>
			<p>
				LA INFORMACI&Oacute;N PERSONAL RECOPILADA POR TELCEL SER&Aacute; ADMINISTRADA 
          		Y UTILIZADA PARA PRESTAR A LOS DISTRIBUIDORES LOS SERVICIOS QUE OFRECE 
          		TELCEL EN ESTE PORTAL Y QUE AQUELLOS SOLICITEN. ASIMISMO, EN EL PORTAL 
          		DE DISTRIBUIDORES DE TELCEL SE HAR&Aacute; DEL CONOCIMIENTO DE LOS DISTRIBUIDORES 
          		SOBRE LOS PRODUCTOS Y SERVICIOS DISPONIBLES.<br>
          		TELCEL PODR&Aacute; PONER CIERTOS DATOS A DISPOSICI&Oacute;N DE SITIOS 
          		RELACIONADOS CON TELCEL PARA FACILITAR LA ELABORACI&Oacute;N DE AN&Aacute;LISIS 
          		ESTAD&Iacute;STICOS, PARA EL ENV&Iacute;O DE CORREO ELECTR&Oacute;NICO 
          		O NEWSLETTER.
			</p>
			<p>
				TELCEL PODR&Aacute; REVELAR INFORMACI&Oacute;N PERSONAL DE SUS DISTRIBUIDORES 
          		&Uacute;NICA Y EXCLUSIVAMENTE EN LOS SIGUIENTES CASOS: (A) EN CUMPLIMIENTO 
          		DE ALGUNA ORDEN EMITIDA POR AUTORIDAD JUDICIAL COMPETENTE, (B) CUANDO 
          		ELLO SEA INDISPENSABLE PARA PROTEGER Y DEFENDER LOS DERECHOS DE PROPIEDAD 
          		INTELECTUAL DE TELCEL, DEL SITIO O DE LOS DISTRIBUIDORES DE TELCEL Y 
          		(C) ACTUANDO BAJO CIRCUNSTANCIAS EXCEPCIONALES PARA PROTEGER LA SEGURIDAD 
          		DE LOS DISTRIBUIDORES DE TELCEL.
			</p>
			<h3>USO DE LOS COOKIES</h3>
			<p>
				EL PORTAL DE DISTRIBUIDORES DE RADIOM&Oacute;VIL DIPSA, S.A. DE C.V., 
          		PODR&Aacute; PREGUNTAR DE MANERA EXPL&Iacute;CITA A LOS DISTRIBUIDORES 
          		CUANDO REQUIERAN INFORMACI&Oacute;N QUE LES IDENTIFIQUE PERSONALMENTE 
          		(EN ADELANTE LA &quot;INFORMACI&Oacute;N PERSONAL&quot;). ESTA INFORMACI&Oacute;N 
          		PUEDE SOLICITARSE AL ENTRAR A UN SITIO O CUANDO SE SOLICITA UN SERVICIO. 
          		RADIOM&Oacute;VIL DIPSA, S.A. DE C.V. PROPORCIONAR&Aacute; AL DISTRIBUIDOR 
          		LOS MEDIOS PARA ASEGURARLE QUE LA INFORMACI&Oacute;N PERSONAL ES CORRECTA 
          		Y ACTUAL.
                <br>
                MODIFICACIONES
			</p>
			<p>
				TELCEL SE RESERVA EL DERECHO DE MODIFICAR EN CUALQUIER MOMENTO LAS 
          		PRESENTES POL&Iacute;TICAS, INDEPENDIENTEMENTE DE LAS RAZONES QUE LA 
          		MOTIVEN. LAS MODIFICACIONES QUE EN SU CASO SE EFECT&Uacute;EN SE HAR&Aacute;N 
          		DEL CONOCIMIENTO DE LOS DISTRIBUIDORES EN ESTE PORTAL.
			</p>
	
		</div>
	</body>

</html>