<html>
	<head>
		<title>Terminos y Condiciones de Uso</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link rel="stylesheet" type="text/css" href="resources/css/pdist.css">
	</head>

	<body>
		<div class="headerTerminos" >
			<p class="informationHeader1">PORTAL DISTRIBUIDORES TELCEL</p>
		 	<p class="informationHeader2">T&eacute;rminos y Condiciones de Uso:</p>
		</div>
		
		<div class="generalContent">
			<h3>LIMITACI&Oacute;N DE RESPONSABILIDAD</h3>
			<p>
				POR MEDIO DE ESTA ADVERTENCIA, RADIOM&Oacute;VIL DIPSA, S.A. DE 
              	C.V., SUS SUBSIDIARIAS Y/O AFILIADAS, INFORMAN A LOS USUARIOS DE 
              	ESTE SITIO (EN ADELANTE LOS &quot;DISTRIBUIDORES&quot;), QUE PONEN 
              	A SU DISPOSICI&Oacute;N DISPOSITIVOS T&Eacute;CNICOS DE ENLACE (TALES 
              	COMO, ENTRE OTROS, LINKS, BANNERS, BOTONES), DIRECTORIOS Y HERRAMIENTAS 
              	DE B&Uacute;SQUEDA QUE LES PERMITEN ACCEDER A P&Aacute;GINAS WEB 
              	PERTENECIENTES A TERCEROS (EN ADELANTE LOS &quot;SITIOS ENLAZADOS&quot;). 
              	LA INSTALACI&Oacute;N DE TALES ENLACES EN ESTE SITIO SE LIMITA A 
              	FACILITAR A LOS DISTRIBUIDORES LA B&Uacute;SQUEDA DE, Y ACCESO, 
              	A LA INFORMACI&Oacute;N DISPONIBLE DE LOS SITIOS ENLAZADOS EN INTERNET, 
              	Y NO PRESUPONE QUE EXISTA NINGUNA CLASE DE V&Iacute;NCULO O ASOCIACI&Oacute;N 
              	ENTRE RADIOM&Oacute;VIL DIPSA, S.A. DE C.V., SUS SUBSIDIARIAS Y/O 
              	AFILIADAS, Y LOS OPERADORES DE LOS SITIOS ENLAZADOS
			</p>
			
			<p>
				RADIOM&Oacute;VIL 
                DIPSA, S.A. DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS NO CONTROLAN, 
                APRUEBAN NI HACEN PROPIOS LOS SERVICIOS, INFORMACI&Oacute;N, DATOS, 
                ARCHIVOS, PRODUCTOS Y CUALQUIER CLASE DE MATERIAL EXISTENTE EN 
                LOS SITIOS ENLAZADOS. LOS DISTRIBUIDORES, POR LO TANTO, DEBEN 
                EXTREMAR LA PRUDENCIA EN LA VALORACI&Oacute;N Y UTILIZACI&Oacute;N 
                DE LOS SERVICIOS, INFORMACI&Oacute;N, DATOS, ARCHIVOS, PRODUCTOS 
                Y CUALQUIER CLASE DE MATERIAL EXISTENTE EN LOS SITIOS ENLAZADOS
			</p>			
			
			<p>
				RADIOM&Oacute;VIL 
                DIPSA, S.A. DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS, NO GARANTIZAN 
                NI ASUMEN RESPONSABILIDAD ALGUNA POR LOS DA&Ntilde;OS Y PERJUICIOS 
                DE TODA CLASE QUE PUEDAN CAUSARSE POR
				
			</p>
			
			<p>
				A.EL FUNCIONAMIENTO, DISPONIBILIDAD, ACCESIBILIDAD O CONTINUIDAD DE LOS 
				SITIOS ENLAZADOS.
			</p>
			
			<p>
				B.EL MANTENIMIENTO 
            	DE LOS SERVICIOS, INFORMACI&Oacute;N, DATOS, ARCHIVOS, PRODUCTOS Y 
            	CUALQUIER CLASE DE MATERIAL EXISTENTE EN LOS SITIOS ENLAZADOS	
			<p>
			
			<p>
				C.OBLIGACIONES Y OFERTAS EXISTENTES EN LOS SITIOS ENLAZADOS
				
			</p>
			
				
			<h3>UTILIDAD</h3>
			<p>
				MEDIANTE LA UTILIZACI&Oacute;N DE ESTA P&Aacute;GINA, 
              	EL DISTRIBUIDOR RECONOCE Y ACEPTA QUE RADIOM&Oacute;VIL DIPSA, S.A. 
              	DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS, NO GARANTIZAN QUE LOS SITIOS 
              	ENLAZADOS O LA INFORMACI&Oacute;N PROPORCIONADA POR TERCEROS, SEAN 
              	&Uacute;TILES PARA LA REALIZACI&Oacute;N DE NINGUNA ACTIVIDAD EN 
              	PARTICULAR.
			</p>
			
			<p>
				MEDIANTE EL USO DE ESTA P&Aacute;GINA, EL DISTRIBUIDOR 
              	RECONOCE Y ACEPTA QUE RADIOM&Oacute;VIL DIPSA, S.A. DE C.V., SUS 
              	SUBSIDIARIAS Y/O AFILIADAS QUEDAN EXCLUIDAS DE CUALQUIER RESPONSABILIDAD 
              	POR LOS DA&Ntilde;OS Y PERJUICIOS QUE PUDIERAN HABER SIDO CAUSADOS 
              	POR LA VERACIDAD DE LA INFORMACI&Oacute;N O CALIDAD DE SERVICIOS 
              	CONTENIDOS U OFRECIDOS POR TERCEROS O QUE SE ENCUENTRE EN LOS SITIOS 
              	ENLAZADOS, O LOS QUE SURJAN CON RELACI&Oacute;N A ESTE SITIO. TANTO 
              	EL ACCESO A ESTA P&Aacute;GINA COMO EL USO QUE PUEDA HACERSE DE 
              	LA INFORMACI&Oacute;N CONTENIDA EN LA MISMA SON EXCLUSIVA RESPONSABILIDAD 
              	DEL DISTRIBUIDOR.
				

			</p>
			<h3>SEGURIDAD</h3>
			<p>
				MEDIANTE EL USO DE ESTA P&Aacute;GINA, EL DISTRIBUIDOR 
              	RECONOCE Y ACEPTA QUE RADIOM&Oacute;VIL DIPSA, S.A. DE C.V., SUS 
              	SUBSIDIARIAS Y/O AFILIADAS, NO GARANTIZAN LA SEGURIDAD DE LOS SITIOS 
              	ENLAZADOS, Y EN PARTICULAR, QUE LOS DISTRIBUIDORES PUEDAN EFECTIVAMENTE 
              	ACCEDER A LAS DISTINTAS P&Aacute;GINAS WEB QUE REPRESENTAN LOS SITIOS 
              	ENLAZADOS, NI QUE A TRAV&Eacute;S DE &Eacute;STOS PUEDAN TRANSMITIR, 
              	DIFUNDIR, ALMACENAR O PONER A DISPOSICI&Oacute;N DE TERCEROS SU 
              	CONTENIDO.	
			</p>
			
			<p>
				MEDIANTE EL USO DE ESTA P&Aacute;GINA, EL DISTRIBUIDOR 
                RECONOCE Y ACEPTA QUE RADIOM&Oacute;VIL DIPSA, S.A. DE C.V., SUS 
                SUBSIDIARIAS Y/O AFILIADAS, QUEDAN EXCLUIDAS DE CUALQUIER RESPONSABILIDAD 
                POR LOS DA&Ntilde;OS Y PERJUICIOS DE TODA NATURALEZA QUE PUDIERAN 
                SER CAUSADOS POR LA FALTA DE SEGURIDAD DE LOS SITIOS ENLAZADOS.
			</p>
			<h3>CALIDAD</h3>
			<p>
				MEDIANTE EL USO DE ESTA P&Aacute;GINA, EL DISTRIBUIDOR 
              	RECONOCE Y ACEPTA QUE RADIOM&Oacute;VIL DIPSA, S.A. DE C.V., SUS 
              	SUBSIDIARIAS Y/O AFILIADAS, NO CONTROLAN Y NO GARANTIZAN LA AUSENCIA 
              	DE VIRUS EN EL CONTENIDO DE LOS SITIOS ENLAZADOS, NI LA AUSENCIA 
              	DE OTROS ELEMENTOS QUE PUDIERAN PRODUCIR ALTERACIONES EN SUS SISTEMAS 
              	INFORM&Aacute;TICOS O EN LOS DOCUMENTOS ELECTR&Oacute;NICOS Y ARCHIVOS 
              	ALMACENADOS EN SUS SISTEMAS INFORM&Aacute;TICOS
			</p>
			<h3>PROPIEDAD INTELECTUAL</h3>
			<p>
				MEDIANTE EL USO DE ESTA P&Aacute;GINA, EL DISTRIBUIDOR 
              	RECONOCE Y ACEPTA QUE RADIOM&Oacute;VIL DIPSA, S.A. DE C.V., SUS 
              	SUBSIDIARIAS Y/O AFILIADAS, QUEDAN EXCLUIDAS DE CUALQUIER RESPONSABILIDAD 
              	QUE PUDIERA SER CAUSADA POR EL USO NO AUTORIZADO DE LAS MARCAS U 
              	OTROS DERECHOS DE PROPIEDAD INTELECTUAL DE TERCEROS O CONTENIDOS 
              	EN LOS SITIOS ENLAZADOS.
			</p>
			<p>
				DE IGUAL MANERA, LAS EVENTUALES REFERENCIAS QUE 
              	SE HAGAN EN ESTA P&Aacute;GINA A CUALQUIER PRODUCTO, SERVICIO, PROCESO, 
              	SITIO ENLAZADO, HIPERTEXTO O CUALQUIER OTRA INFORMACI&Oacute;N EN 
              	LA QUE SE UTILICEN MARCAS, SIGNOS DISTINTIVOS Y/O DOMINIOS, EL NOMBRE 
              	COMERCIAL O EL NOMBRE DEL FABRICANTE, SUMINISTRADOR, ETC., QUE SEAN 
              	TITULARIDAD DE TERCEROS, EN NING&Uacute;N MOMENTO CONSTITUIR&Aacute;N, 
              	NI IMPLICAR&Aacute;N RESPALDO O RECOMENDACI&Oacute;N ALGUNA POR 
              	PARTE DE RADIOM&Oacute;VIL DIPSA, S.A. DE C.V., SUS SUBSIDIARIAS 
              	Y/O AFILIADAS Y EN NING&Uacute;N CASO RADIOM&Oacute;VIL DIPSA, S.A. 
              	DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS SE ASIGNAN PROPIEDAD NI 
              	RESPONSABILIDAD SOBRE LOS MISMOS.
			</p>
			<h3>ELEMENTOS DE LAS P&Aacute;GINAS</h3>
			<p>
				ES PROBABLE QUE PARA PROPORCIONAR LA INFORMACI&Oacute;N 
              	CONTENIDA EN ESTE PORTAL, TAL COMO DIBUJOS, DISE&Ntilde;OS, SONIDO, 
              	VIDEOS, TEXTOS, FOTOGRAF&Iacute;AS, ETC., RADIOM&Oacute;VIL DIPSA,, 
              	S.A. DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS, HUBIEREN CONTRATADO 
              	A TERCEROS PARA REALIZAR LOS ESTUDIOS E INVESTIGACIONES CORRESPONDIENTES, 
              	AS&Iacute; COMO LOS DIBUJOS, DISE&Ntilde;OS, SONIDOS, VIDEOS, TEXTOS, 
              	O FOTOGRAF&Iacute;AS, QUE SE MUESTREN EN EL PORTAL. RADIOM&Oacute;VIL 
              	DIPSA, S.A. DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS, ADVIERTEN QUE 
              	AL NO SER DE SU TITULARIDAD NI DESARROLLO TODA LA INFORMACI&Oacute;N 
              	CONTENIDA EN EL PORTAL, ALGUNOS DE LOS TEXTOS, GR&Aacute;FICOS, 
              	V&Iacute;NCULOS Y/O EL CONTENIDO DE ALGUNOS ART&Iacute;CULOS INCLUIDOS 
              	EN EL MISMO PODR&Iacute;AN NO SER VERACES O NO ESTAR ACTUALIZADOS, 
              	POR LO QUE RADIOM&Oacute;VIL DIPSA, S.A. DE C.V., SUS SUBSIDIARIAS 
              	Y/O AFILIADAS, NO SE HACEN RESPONSABLES.
			</p>
			<h3>CONFIDENCIALIDAD</h3>
			<p>
				POR MEDIO DE ESTE PORTAL, RADIOM&Oacute;VIL DIPSA, 
              	S.A. DE C.V., HABR&Aacute; DE PROPORCIONAR AL DISTRIBUIDOR INFORMACI&Oacute;N 
              	CONFIDENCIALCON EL FIN DE QUE EL DISTRIBUIDOR PRESTE ADECUADAMENTE 
              	SUS SERVICIOS, DE ACUERDO CON LAS INSTRUCCIONES DE RADIOM&Oacute;VIL 
              	DIPSA, S.A. DE C.V. O DE CUALQUIER TERCERO QUE &Eacute;STE DESIGNE 
              	POR ESCRITO.
			</p>
			<p>
				EL DISTRIBUIDOR HABR&Aacute; DE TRATAR COMO CONFIDENCIAL 
              	CUALQUIER INFORMACI&Oacute;N, YA SEA ESCRITA O VERBAL QUE RECIBA 
              	DE RADIOM&Oacute;VIL DIPSA, S.A. DE C.V., Y QUE DE MANERA ENUNCIATIVA 
              	Y NO LIMITATIVA SE LISTA A CONTINUACI&Oacute;N: INFORMACI&Oacute;N 
              	PROPIETARIA Y CONFIDENCIAL, FINANCIERA, T&Eacute;CNICA, COMERCIAL, 
              	ESTRAT&Eacute;GICA U OTRA INFORMACI&Oacute;N RELACIONADA CON LOS 
              	PROYECTOS Y NEGOCIOS, PRODUCTOS Y SERVICIOS, M&Eacute;TODOS, SISTEMAS, 
              	PLANES DE NEGOCIOS O M&Eacute;TODOS DE MERCADEO Y ESTRATEGIAS, CAMPA&Ntilde;AS 
              	DE PUBLICIDAD, INCLUYENDO MATERIAL GR&Aacute;FICO, DISE&Ntilde;OS, 
              	ESQUEMAS, Y CUALQUIER OTRA INFORMACI&Oacute;N O MATERIAL DE RADIOM&Oacute;VIL 
              	DIPSA, S.A. DE C.V. QUE PUDIERA INCLUIR DATOS DE LAS PROMOCIONES, 
              	DE LOS PLANES TARIFARIOS, DE LOS PLANES DE CAPACITACI&Oacute;N, 
              	DE LAS TARIFAS DE COMISIONES, COMPARATIVOS DE LA COMPETENCIA, AS&Iacute; 
              	COMO PROGRAMAS DE DESARROLLO Y PLANES DE NEGOCIOS DE RADIOM&Oacute;VIL 
              	DIPSA, S.A. DE C.V., O CUALQUIER DOCUMENTO Y/O MEDIO ELECTR&Oacute;NICO 
              	DONDE SE HAGA CONSTAR LA CITADA INFORMACI&Oacute;N (EN CONJUNTO, 
              	&quot;INFORMACI&Oacute;N CONFIDENCIAL&quot;.
			</p>
			<p>
				CUALQUIER DIVULGACI&Oacute;N DE INFORMACI&Oacute;N 
	            CONFIDENCIAL EN FORMA DISTINTA A LA EXPRESAMENTE AUTORIZADA POR 
              	RADIOM&Oacute;VIL DIPSA, S.A. DE C.V. EN CADA CASO, REQUIERE DE 
              	LA APROBACI&Oacute;N PREVIA Y POR ESCRITO DE RADIOM&Oacute;VIL DIPSA, 
              	S.A. DE C.V.
			</p>
			<p>
				SALVO QUE MEDIE UN REQUERIMIENTO DE AUTORIDAD COMPETENTE, 
              	EL DISTRIBUIDOR SE ABSTENDR&Aacute; DE DIVULGAR INFORMACI&Oacute;N 
              	CONFIDENCIAL A CUALQUIER PERSONA. EN TODO CASO, EL DISTRIBUIDOR 
              	SER&Aacute; RESPONSABLE FRENTE A RADIOM&Oacute;VIL DIPSA, S.A. DE 
              	C.V., DE LA DIVULGACI&Oacute;N DE INFORMACI&Oacute;N CONFIDENCIAL.
			</p>
			<p>
				SIN PERJUICIO DE LAS DEM&Aacute;S OBLIGACIONES QUE 
              	ASUME, EL DISTRIBUIDOR SE OBLIGA CON RADIOM&Oacute;VIL DIPSA, S.A. 
              	DE C.V. A QUE HABR&Aacute; DE: (I) MANTENER EN ESTRICTA CONFIDENCIA 
              	LA INFORMACI&Oacute;N CONFIDENCIAL; (II) ABSTENERSE DE COPIAR O 
              	DIVULGAR LA INFORMACI&Oacute;N; (III) USAR LA INFORMACI&Oacute;N 
              	CONFIDENCIAL S&Oacute;LO PARA LOS FINES PARA LOS QUE EXPRESAMENTE 
              	LE HAYA SIDO PROPORCIONADA; (IV) TOMAR LAS MEDIDAS NECESARIAS, INCLUYENDO, 
              	ENTRE OTRAS, LA CAPACITACI&Oacute;N RESPECTO DE LAS OBLIGACIONES 
              	DE CONFIDENCIALIDAD AQU&Iacute; CONTENIDAS; Y (V) DEVOLVER LA INFORMACI&Oacute;N 
              	CONFIDENCIAL CUANDO LO SOLICITE RADIOM&Oacute;VIL DIPSA, S.A. DE 
              	C.V., SIN CONSERVAR COPIAS O DUPLICADOS.
				
			</p>
			<h3>RELACI&Oacute;N LABORAL</h3>
			<p>
				ENTRE EL DISTRIBUIDOR Y RADIOM&Oacute;VIL DIPSA, 
              	S.A. DE C.V. NO EXISTE NING&Uacute;N TIPO DE RELACI&Oacute;N LABORAL, 
              	SUBORDINACI&Oacute;N O CREACI&Oacute;N DE CUALQUIER TIPO DE SOCIEDAD, 
              	ASOCIACI&Oacute;N O FRANQUICIA
			</p>
			<h3>LEY APLICABLE Y JURISDICCI&Oacute;N</h3>
			<p>
				EL DISTRIBUIDOR AL HACER USO DE LAS APLICACIONES 
              	CONTENIDAS EN EL PORTAL DE DISTRIBUIDORES DE TELCEL, ACEPTA DE MANERA 
              	EXPRESA, SOMETERSE EN CASO DE CUALQUIER CONTROVERSIA, A LA JURISDICCI&Oacute;N 
              	DE LOS TRIBUNALES DE LA CIUDAD DE M&Eacute;XICO, ESTADOS UNIDOS 
              	MEXICANOS, AS&Iacute; COMO LAS LEYES APLICABLES PARA EL CASO CONCRETO 
              	VIGENTES EN DICHO LUGAR, RENUNCIANDO EXPRESAMENTE A CUALQUIER OTRA 
              	JURISDICCI&Oacute;N QUE POR MOTIVO DE SU NACIONALIDAD O DOMICILIO 
              	LE PUDIERA CORRESPONDER.
			</p>	

	
			
		</div>
		



	</body>	




</html>